import montserrat from '@/assets/fonts/montserrat-font';
import 'assets/styles/globals.css';
import 'assets/icons/fontawesome/css/fontawesome.css';
import 'assets/icons/fontawesome/css/brands.css';
import 'assets/icons/fontawesome/css/solid.css';

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} text-mainTextColor`}>{children}</body>
		</html>
	);
}
